// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class ServicePackage
{
    public int PackageId { get; set; }

    public string PackageName { get; set; }

    public string Description { get; set; }

    public decimal Fee { get; set; }

    public decimal? DiscountPercentage { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual ICollection<Business> Businesses { get; set; } = new List<Business>();
}