// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Ticket
{
    public int TicketId { get; set; }

    public string Barcode { get; set; }

    public decimal Price { get; set; }

    public int? Quantity { get; set; }

    public string SeatNumber { get; set; }

    public DateTime? StartDate { get; set; }

    public int? SellerId { get; set; }

    public int? CategoryId { get; set; }

    public string PdfFile { get; set; }

    public string Status { get; set; }

    public DateTime? PostedAt { get; set; }

    public int? ApprovedBy { get; set; }

    public DateTime? ApprovalDate { get; set; }

    public string Description { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual User Seller { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}