// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Address { get; set; }

    public string ImageUrl { get; set; }

    public decimal? AverageRating { get; set; }

    public int? RatingCount { get; set; }

    public DateTime? MembershipDate { get; set; }

    public string MembershipStatus { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string BankName { get; set; }

    public string BankAccount { get; set; }

    public int? RoleId { get; set; }

    public int? WalletId { get; set; }

    public virtual ICollection<Feedback> FeedbackBuyers { get; set; } = new List<Feedback>();

    public virtual ICollection<Feedback> FeedbackSellers { get; set; } = new List<Feedback>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual UserRole Role { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();

    public virtual Wallet Wallet { get; set; }

    public virtual ICollection<Wallet> Wallets { get; set; } = new List<Wallet>();

    public virtual ICollection<WithdrawalRequest> WithdrawalRequests { get; set; } = new List<WithdrawalRequest>();
}