// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class WithdrawalRequest
{
    public int WithdrawalRequestId { get; set; }

    public int UserId { get; set; }

    public decimal Amount { get; set; }

    public DateTime? RequestDate { get; set; }

    public string Status { get; set; }

    public virtual User User { get; set; }
}